"""
PARIKA Core - ProviderManager Component

Defines execution limits supported by a ProviderModel.

ModelLimits represents the normalized execution constraints exposed by a
model. These limits are immutable and provider-independent, allowing the
rest of the PARIKA Core to reason about model capabilities without
provider-specific logic.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ModelLimits:
    """
    Immutable execution limits supported by a ProviderModel.

    Attributes:
        context_window:
            Maximum number of input tokens supported by the model.
            None indicates that the provider does not expose this
            information.

        max_output_tokens:
            Maximum number of output tokens that can be generated by the
            model in a single request. None indicates that the provider
            does not expose this information.
    """

    context_window: int | None = None
    max_output_tokens: int | None = None