###############################################################################
# PARIKA Workspace Configuration
#
# Project-specific overrides.
###############################################################################
